//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DataAccess.DataBase.Interfacies;

namespace DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class City: DBDictionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.BankDepartment = new HashSet<BankDepartment>();
        }
    
        public int Id { get; set; }
        public override string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankDepartment> BankDepartment { get; set; }
    }
}
