//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DataBase
{
    public partial class CurrencyRateByTime
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        public int BankDepartmentId { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Sale { get; set; }
        public double Purchase { get; set; }
    
        public virtual BankDepartment BankDepartment { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
